/*Salesperson with the highest sales amount.*/
SELECT p.Salesperson,s.SPID,SUM(s.amount) as SalesAmount from SALES s
JOIN people p ON s.SPID=p.SPID
GROUP BY s.SPID
ORDER BY SalesAmount DESC
LIMIT 1;
/*Average sales amount per salesperson*/
SELECT p.Salesperson,s.SPID,ROUND(AVG(s.amount),2)as SalesAmount from SALES s
JOIN people p ON s.SPID=p.SPID
GROUP BY s.SPID
ORDER BY SalesAmount DESC;

/*Sales performance of each salesperson by region*/
SELECT p.Salesperson, g.Region, SUM(s.Amount) AS TotalSalesAmount
FROM Sales s
JOIN People p ON s.SPID = p.SPID
JOIN geo g ON s.GeoID = g.GeoID
GROUP BY p.Salesperson, g.Region;
/*Total sales amount generated by each team*/
SELECT p.Team, SUM(s.Amount) AS TotalSalesAmount,  ROUND((SUM(s.Amount) / (SELECT SUM(Amount) FROM Sales)) * 100,2)AS PercentageSales
FROM Sales s
JOIN People p ON s.SPID = p.SPID 
GROUP BY p.Team;
